// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CarTouchScreenMiniDisplay

#include "../ui.h"

lv_obj_t * uic_ResetInclinometer;
lv_obj_t * uic_PajeroRoll;
lv_obj_t * uic_PajeroPitch;
lv_obj_t * ui_InclinometerNew = NULL;
lv_obj_t * ui_PajeroPitch = NULL;
lv_obj_t * ui_PajeroRoll = NULL;
lv_obj_t * ui_ResetInclinometer = NULL;
// event funtions
void ui_event_InclinometerNew(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Inclinometer, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 50, 0, &ui_Inclinometer_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Wifi, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_Wifi_screen_init);
    }
}

// build funtions

void ui_InclinometerNew_screen_init(void)
{
    ui_InclinometerNew = lv_obj_create(NULL);
    lv_obj_set_style_radius(ui_InclinometerNew, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_InclinometerNew, lv_color_hex(0x3541D6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InclinometerNew, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_InclinometerNew, lv_color_hex(0xE09514), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_InclinometerNew, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_InclinometerNew, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_InclinometerNew, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PajeroPitch = lv_img_create(ui_InclinometerNew);
    lv_img_set_src(ui_PajeroPitch, &ui_img_rollpajero2_zip_png);
    lv_obj_set_width(ui_PajeroPitch, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PajeroPitch, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PajeroPitch, -1);
    lv_obj_set_y(ui_PajeroPitch, -45);
    lv_obj_set_align(ui_PajeroPitch, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_PajeroPitch, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PajeroPitch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PajeroPitch, 170);

    ui_PajeroRoll = lv_img_create(ui_InclinometerNew);
    lv_img_set_src(ui_PajeroRoll, &ui_img_555283202);
    lv_obj_set_width(ui_PajeroRoll, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PajeroRoll, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PajeroRoll, -1);
    lv_obj_set_y(ui_PajeroRoll, -105);
    lv_obj_set_align(ui_PajeroRoll, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PajeroRoll, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_PajeroRoll, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_PajeroRoll, 250);

    ui_ResetInclinometer = lv_btn_create(ui_InclinometerNew);
    lv_obj_set_width(ui_ResetInclinometer, 80);
    lv_obj_set_height(ui_ResetInclinometer, 75);
    lv_obj_set_x(ui_ResetInclinometer, 129);
    lv_obj_set_y(ui_ResetInclinometer, -189);
    lv_obj_set_align(ui_ResetInclinometer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ResetInclinometer, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ResetInclinometer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ResetInclinometer, 1000, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ResetInclinometer, lv_color_hex(0xDFFF0A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ResetInclinometer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ResetInclinometer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_ResetInclinometer, 70, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_ResetInclinometer, 170, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ResetInclinometer, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_InclinometerNew, ui_event_InclinometerNew, LV_EVENT_ALL, NULL);
    uic_PajeroPitch = ui_PajeroPitch;
    uic_PajeroRoll = ui_PajeroRoll;
    uic_ResetInclinometer = ui_ResetInclinometer;

}

void ui_InclinometerNew_screen_destroy(void)
{
    if(ui_InclinometerNew) lv_obj_del(ui_InclinometerNew);

    // NULL screen variables
    ui_InclinometerNew = NULL;
    uic_PajeroPitch = NULL;
    ui_PajeroPitch = NULL;
    uic_PajeroRoll = NULL;
    ui_PajeroRoll = NULL;
    uic_ResetInclinometer = NULL;
    ui_ResetInclinometer = NULL;

}
