// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CarTouchScreenMiniDisplay

#ifndef UI_INCLINOMETERGRAPH_H
#define UI_INCLINOMETERGRAPH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_InclinometerGraph
extern void ui_InclinometerGraph_screen_init(void);
extern void ui_InclinometerGraph_screen_destroy(void);
extern void ui_event_InclinometerGraph(lv_event_t * e);
extern lv_obj_t * ui_InclinometerGraph;
extern lv_obj_t * ui_RollGraph;
extern lv_obj_t * ui_PitchGraph;
extern lv_obj_t * ui_TemperatureReading;
extern lv_obj_t * ui_TemperatureName;
// CUSTOM VARIABLES
extern lv_obj_t * uic_InclinometerGraph;
extern lv_obj_t * uic_RollGraph;
extern lv_obj_t * uic_PitchGraph;
extern lv_obj_t * uic_TemperatureReading;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

