// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CarTouchScreenMiniDisplay

#ifndef UI_INCLINOMETERNEW_H
#define UI_INCLINOMETERNEW_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_InclinometerNew
extern void ui_InclinometerNew_screen_init(void);
extern void ui_InclinometerNew_screen_destroy(void);
extern void ui_event_InclinometerNew(lv_event_t * e);
extern lv_obj_t * ui_InclinometerNew;
extern lv_obj_t * ui_PajeroPitch;
extern lv_obj_t * ui_PajeroRoll;
extern lv_obj_t * ui_ResetInclinometer;
extern lv_obj_t * ui_RollTextNew;
extern lv_obj_t * ui_PitchTextNew;
// CUSTOM VARIABLES
extern lv_obj_t * uic_PajeroPitch;
extern lv_obj_t * uic_PajeroRoll;
extern lv_obj_t * uic_ResetInclinometer;
extern lv_obj_t * uic_RollTextNew;
extern lv_obj_t * uic_PitchTextNew;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

