// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CarTouchScreenMiniDisplay

#ifndef UI_MAINCONFIGSCREEN_H
#define UI_MAINCONFIGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainConfigScreen
extern void ui_MainConfigScreen_screen_init(void);
extern void ui_MainConfigScreen_screen_destroy(void);
extern void ui_event_MainConfigScreen(lv_event_t * e);
extern lv_obj_t * ui_MainConfigScreen;
extern void ui_event_Brightness(lv_event_t * e);
extern lv_obj_t * ui_Brightness;
extern lv_obj_t * ui_BrightnessLabel;
extern void ui_event_StoreBrightness(lv_event_t * e);
extern lv_obj_t * ui_StoreBrightness;
extern lv_obj_t * ui_SaveBrightness;
extern void ui_event_EraseMemory(lv_event_t * e);
extern lv_obj_t * ui_EraseMemory;
extern lv_obj_t * ui_EraseMem;
extern void ui_event_WifiConfig(lv_event_t * e);
extern lv_obj_t * ui_WifiConfig;
extern lv_obj_t * ui_WifiConfigLabel;
extern void ui_event_SoftwareUpdate(lv_event_t * e);
extern lv_obj_t * ui_SoftwareUpdate;
extern lv_obj_t * ui_SoftwareUpdateLabel;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Brightness;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

