// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CarTouchScreenMiniDisplay

#ifndef UI_MANUALWIFI_H
#define UI_MANUALWIFI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ManualWifi
extern void ui_ManualWifi_screen_init(void);
extern void ui_ManualWifi_screen_destroy(void);
extern void ui_event_ManualWifi(lv_event_t * e);
extern lv_obj_t * ui_ManualWifi;
extern lv_obj_t * ui_WifiKeyboard;
extern lv_obj_t * ui_WifiAPList;
extern lv_obj_t * ui_WifiPassword;
extern void ui_event_Connect(lv_event_t * e);
extern lv_obj_t * ui_Connect;
extern lv_obj_t * ui_WifiConnectFeedback;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ManualWifi;
extern lv_obj_t * uic_WifiKeyboard;
extern lv_obj_t * uic_WifiAPList;
extern lv_obj_t * uic_WifiPassword;
extern lv_obj_t * uic_Connect;
extern lv_obj_t * uic_WifiConnectFeedback;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

