// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CarTouchScreenMiniDisplay

#ifndef UI_OTAUPDATE_H
#define UI_OTAUPDATE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_OTAUpdate
extern void ui_OTAUpdate_screen_init(void);
extern void ui_OTAUpdate_screen_destroy(void);
extern void ui_event_OTAUpdate(lv_event_t * e);
extern lv_obj_t * ui_OTAUpdate;
extern void ui_event_SoftwarUpdate_SoftwarUpdate(lv_event_t * e);
extern lv_obj_t * ui_SoftwarUpdate;
extern lv_obj_t * ui_SoftwareUpdateFeedback;
extern lv_obj_t * ui_IPLabel;
extern lv_obj_t * ui_IPString;
// CUSTOM VARIABLES
extern lv_obj_t * uic_OTAUpdate;
extern lv_obj_t * uic_SoftwareUpdateFeedback;
extern lv_obj_t * uic_IPString;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

