// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CarTouchScreenMiniDisplay

#ifndef UI_OPTIONS_H
#define UI_OPTIONS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Options
extern void ui_Options_screen_init(void);
extern void ui_Options_screen_destroy(void);
extern void ui_event_Options(lv_event_t * e);
extern lv_obj_t * ui_Options;
extern void ui_event_SoftwarUpdate_SoftwarUpdate(lv_event_t * e);
extern lv_obj_t * ui_SoftwarUpdate;
extern lv_obj_t * ui_SoftwareUpdateFeedback;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SoftwareUpdateFeedback;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

