// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CarTouchScreenMiniDisplay

#include "../ui.h"

lv_obj_t * uic_WifiConnectFeedback;
lv_obj_t * uic_Connect;
lv_obj_t * uic_WifiPassword;
lv_obj_t * uic_WifiAPList;
lv_obj_t * uic_WifiKeyboard;
lv_obj_t * uic_Wifi;
lv_obj_t * ui_Wifi = NULL;
lv_obj_t * ui_WifiKeyboard = NULL;
lv_obj_t * ui_WifiAPList = NULL;
lv_obj_t * ui_WifiPassword = NULL;
lv_obj_t * ui_Connect = NULL;
lv_obj_t * ui_WifiConnectFeedback = NULL;
// event funtions
void ui_event_Wifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Inclinometer, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_Inclinometer_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_OTAUpdate, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_OTAUpdate_screen_init);
    }
}

void ui_event_Connect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        UI_ConnectWifiCallback(e);
    }
}

// build funtions

void ui_Wifi_screen_init(void)
{
    ui_Wifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiKeyboard = lv_keyboard_create(ui_Wifi);
    lv_obj_set_width(ui_WifiKeyboard, 425);
    lv_obj_set_height(ui_WifiKeyboard, 138);
    lv_obj_set_x(ui_WifiKeyboard, 1);
    lv_obj_set_y(ui_WifiKeyboard, 61);
    lv_obj_set_align(ui_WifiKeyboard, LV_ALIGN_CENTER);

    ui_WifiAPList = lv_dropdown_create(ui_Wifi);
    lv_dropdown_set_options(ui_WifiAPList, "WifiA\nWifiB\nWifiC\n");
    lv_obj_set_width(ui_WifiAPList, 290);
    lv_obj_set_height(ui_WifiAPList, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiAPList, -4);
    lv_obj_set_y(ui_WifiAPList, -141);
    lv_obj_set_align(ui_WifiAPList, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiAPList, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_WifiAPList, &ui_font_SmallerEmblemaOne, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiPassword = lv_textarea_create(ui_Wifi);
    lv_obj_set_width(ui_WifiPassword, 315);
    lv_obj_set_height(ui_WifiPassword, 64);
    lv_obj_set_x(ui_WifiPassword, -4);
    lv_obj_set_y(ui_WifiPassword, -68);
    lv_obj_set_align(ui_WifiPassword, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_WifiPassword, "Placeholder...");
    lv_obj_set_style_text_font(ui_WifiPassword, &ui_font_SmallerEmblemaOne, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Connect = lv_btn_create(ui_Wifi);
    lv_obj_set_width(ui_Connect, 387);
    lv_obj_set_height(ui_Connect, 94);
    lv_obj_set_x(ui_Connect, 0);
    lv_obj_set_y(ui_Connect, 185);
    lv_obj_set_align(ui_Connect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Connect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Connect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Connect, lv_color_hex(0xE09514), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Connect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiConnectFeedback = lv_label_create(ui_Wifi);
    lv_obj_set_width(ui_WifiConnectFeedback, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiConnectFeedback, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiConnectFeedback, -1);
    lv_obj_set_y(ui_WifiConnectFeedback, 179);
    lv_obj_set_align(ui_WifiConnectFeedback, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WifiConnectFeedback, "Connect");
    lv_obj_set_style_text_font(ui_WifiConnectFeedback, &ui_font_SmallerEmblemaOne, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_keyboard_set_textarea(ui_WifiKeyboard, ui_WifiPassword);
    lv_obj_add_event_cb(ui_Connect, ui_event_Connect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Wifi, ui_event_Wifi, LV_EVENT_ALL, NULL);
    uic_Wifi = ui_Wifi;
    uic_WifiKeyboard = ui_WifiKeyboard;
    uic_WifiAPList = ui_WifiAPList;
    uic_WifiPassword = ui_WifiPassword;
    uic_Connect = ui_Connect;
    uic_WifiConnectFeedback = ui_WifiConnectFeedback;

}

void ui_Wifi_screen_destroy(void)
{
    if(ui_Wifi) lv_obj_del(ui_Wifi);

    // NULL screen variables
    uic_Wifi = NULL;
    ui_Wifi = NULL;
    uic_WifiKeyboard = NULL;
    ui_WifiKeyboard = NULL;
    uic_WifiAPList = NULL;
    ui_WifiAPList = NULL;
    uic_WifiPassword = NULL;
    ui_WifiPassword = NULL;
    uic_Connect = NULL;
    ui_Connect = NULL;
    uic_WifiConnectFeedback = NULL;
    ui_WifiConnectFeedback = NULL;

}
