// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CarTouchScreenMiniDisplay

#include "../ui.h"

lv_obj_t * uic_TriggerWifiScan1;
lv_obj_t * uic_TriggerWifiScan;
lv_obj_t * uic_myIPString;
lv_obj_t * uic_GatewayIP;
lv_obj_t * uic_ConnectedWifiSSID;
lv_obj_t * uic_ProvisioningText;
lv_obj_t * uic_EnableProvisioning;
lv_obj_t * uic_Wifi;
lv_obj_t * ui_Wifi = NULL;
lv_obj_t * ui_EnableProvisioning = NULL;
lv_obj_t * ui_ProvisioningText = NULL;
lv_obj_t * ui_ConnectedWifiSSID = NULL;
lv_obj_t * ui_GatewayIP = NULL;
lv_obj_t * ui_myIPString = NULL;
lv_obj_t * ui_ManualConnect = NULL;
lv_obj_t * ui_Manual_Connect_Text = NULL;
lv_obj_t * ui_TriggerWifiScan = NULL;
lv_obj_t * ui_TriggerWifiScan1 = NULL;
// event funtions
void ui_event_Wifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MainConfigScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_MainConfigScreen_screen_init);
    }
}

void ui_event_ManualConnect(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ManualWifi, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ManualWifi_screen_init);
    }
}

void ui_event_TriggerWifiScan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        UI_TriggerWifiScan(e);
    }
}

// build funtions

void ui_Wifi_screen_init(void)
{
    ui_Wifi = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Wifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EnableProvisioning = lv_switch_create(ui_Wifi);
    lv_obj_set_width(ui_EnableProvisioning, 115);
    lv_obj_set_height(ui_EnableProvisioning, 45);
    lv_obj_set_x(ui_EnableProvisioning, -141);
    lv_obj_set_y(ui_EnableProvisioning, -75);
    lv_obj_set_align(ui_EnableProvisioning, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_EnableProvisioning, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EnableProvisioning, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_EnableProvisioning, lv_color_hex(0x868686), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EnableProvisioning, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_EnableProvisioning, lv_color_hex(0x868686), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_EnableProvisioning, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_EnableProvisioning, lv_color_hex(0xE09514), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_EnableProvisioning, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ProvisioningText = lv_label_create(ui_Wifi);
    lv_obj_set_width(ui_ProvisioningText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProvisioningText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ProvisioningText, 69);
    lv_obj_set_y(ui_ProvisioningText, -74);
    lv_obj_set_align(ui_ProvisioningText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ProvisioningText, "Provisioning is Disabled!");
    lv_obj_set_style_text_font(ui_ProvisioningText, &ui_font_SmallerEmblemaOne, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectedWifiSSID = lv_label_create(ui_Wifi);
    lv_obj_set_width(ui_ConnectedWifiSSID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConnectedWifiSSID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConnectedWifiSSID, 62);
    lv_obj_set_y(ui_ConnectedWifiSSID, -23);
    lv_obj_set_align(ui_ConnectedWifiSSID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConnectedWifiSSID, "Wifi SSID");
    lv_obj_set_style_text_font(ui_ConnectedWifiSSID, &ui_font_SmallerEmblemaOne, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GatewayIP = lv_label_create(ui_Wifi);
    lv_obj_set_width(ui_GatewayIP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GatewayIP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GatewayIP, 1);
    lv_obj_set_y(ui_GatewayIP, 25);
    lv_obj_set_align(ui_GatewayIP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GatewayIP, "255.255.255.255");
    lv_obj_set_style_text_font(ui_GatewayIP, &ui_font_HeadingDegree, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_myIPString = lv_label_create(ui_Wifi);
    lv_obj_set_width(ui_myIPString, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_myIPString, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_myIPString, 1);
    lv_obj_set_y(ui_myIPString, 85);
    lv_obj_set_align(ui_myIPString, LV_ALIGN_CENTER);
    lv_label_set_text(ui_myIPString, "255.255.255.255");
    lv_obj_set_style_text_font(ui_myIPString, &ui_font_HeadingDegree, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ManualConnect = lv_btn_create(ui_Wifi);
    lv_obj_set_width(ui_ManualConnect, 414);
    lv_obj_set_height(ui_ManualConnect, 105);
    lv_obj_set_x(ui_ManualConnect, 1);
    lv_obj_set_y(ui_ManualConnect, 181);
    lv_obj_set_align(ui_ManualConnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ManualConnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ManualConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ManualConnect, lv_color_hex(0xE09514), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ManualConnect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Manual_Connect_Text = lv_label_create(ui_Wifi);
    lv_obj_set_width(ui_Manual_Connect_Text, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Manual_Connect_Text, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Manual_Connect_Text, -3);
    lv_obj_set_y(ui_Manual_Connect_Text, -47);
    lv_obj_set_align(ui_Manual_Connect_Text, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_Manual_Connect_Text, "Manual Config");
    lv_obj_set_style_text_font(ui_Manual_Connect_Text, &ui_font_SmallerEmblemaOne, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TriggerWifiScan = lv_btn_create(ui_Wifi);
    lv_obj_set_width(ui_TriggerWifiScan, 414);
    lv_obj_set_height(ui_TriggerWifiScan, 105);
    lv_obj_set_x(ui_TriggerWifiScan, -1);
    lv_obj_set_y(ui_TriggerWifiScan, -182);
    lv_obj_set_align(ui_TriggerWifiScan, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TriggerWifiScan, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TriggerWifiScan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TriggerWifiScan, lv_color_hex(0xE09514), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TriggerWifiScan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TriggerWifiScan1 = lv_label_create(ui_Wifi);
    lv_obj_set_width(ui_TriggerWifiScan1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TriggerWifiScan1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TriggerWifiScan1, 1);
    lv_obj_set_y(ui_TriggerWifiScan1, -394);
    lv_obj_set_align(ui_TriggerWifiScan1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_TriggerWifiScan1, "Scan for Wifi");
    lv_obj_set_style_text_font(ui_TriggerWifiScan1, &ui_font_SmallerEmblemaOne, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ManualConnect, ui_event_ManualConnect, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TriggerWifiScan, ui_event_TriggerWifiScan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Wifi, ui_event_Wifi, LV_EVENT_ALL, NULL);
    uic_Wifi = ui_Wifi;
    uic_EnableProvisioning = ui_EnableProvisioning;
    uic_ProvisioningText = ui_ProvisioningText;
    uic_ConnectedWifiSSID = ui_ConnectedWifiSSID;
    uic_GatewayIP = ui_GatewayIP;
    uic_myIPString = ui_myIPString;
    uic_TriggerWifiScan = ui_TriggerWifiScan;
    uic_TriggerWifiScan1 = ui_TriggerWifiScan1;

}

void ui_Wifi_screen_destroy(void)
{
    if(ui_Wifi) lv_obj_del(ui_Wifi);

    // NULL screen variables
    uic_Wifi = NULL;
    ui_Wifi = NULL;
    uic_EnableProvisioning = NULL;
    ui_EnableProvisioning = NULL;
    uic_ProvisioningText = NULL;
    ui_ProvisioningText = NULL;
    uic_ConnectedWifiSSID = NULL;
    ui_ConnectedWifiSSID = NULL;
    uic_GatewayIP = NULL;
    ui_GatewayIP = NULL;
    uic_myIPString = NULL;
    ui_myIPString = NULL;
    ui_ManualConnect = NULL;
    ui_Manual_Connect_Text = NULL;
    uic_TriggerWifiScan = NULL;
    ui_TriggerWifiScan = NULL;
    uic_TriggerWifiScan1 = NULL;
    ui_TriggerWifiScan1 = NULL;

}
