// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CarTouchScreenMiniDisplay

#ifndef _CARTOUCHSCREENMINIDISPLAY_UI_H
#define _CARTOUCHSCREENMINIDISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_MainConfigScreen.h"
#include "screens/ui_MemoryEraseValidation.h"
#include "screens/ui_OTAUpdate.h"
#include "screens/ui_Wifi.h"
#include "screens/ui_ManualWifi.h"
#include "screens/ui_InclinometerGraph.h"
#include "screens/ui_Inclinometer.h"
#include "screens/ui_InclinometerNew.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_rollpajero2_reduced_png);    // assets/RollPajero2_reduced.png
LV_IMG_DECLARE(ui_img_rollreduced_png);    // assets/RollReduced.png

// FONTS
LV_FONT_DECLARE(ui_font_Nabla_Big);
LV_FONT_DECLARE(ui_font_HeadingDegree);
LV_FONT_DECLARE(ui_font_SmallerEmblemaOne);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
