// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CarTouchScreenMiniDisplay

#ifndef _CARTOUCHSCREENMINIDISPLAY_UI_H
#define _CARTOUCHSCREENMINIDISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Inclinometer.h"
#include "screens/ui_Temperature.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_scale_revamp_png);    // assets/Scale_revamp.png

// FONTS
LV_FONT_DECLARE(ui_font_Nabla_Big);
LV_FONT_DECLARE(ui_font_HeadingDegree);
LV_FONT_DECLARE(ui_font_SmallerEmblemaOne);

// UI INIT
void ui_init(void);
void ui_destroy(void);
void ui_relocalize(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
