// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CarTouchScreenMiniDisplay

#include "../ui.h"

// COMPONENT SoftwarUpdate

lv_obj_t * ui_SoftwarUpdate_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_SoftwarUpdate;
    cui_SoftwarUpdate = lv_btn_create(comp_parent);
    lv_obj_set_width(cui_SoftwarUpdate, 100);
    lv_obj_set_height(cui_SoftwarUpdate, 50);
    lv_obj_set_x(cui_SoftwarUpdate, -5);
    lv_obj_set_y(cui_SoftwarUpdate, -156);
    lv_obj_set_align(cui_SoftwarUpdate, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_SoftwarUpdate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(cui_SoftwarUpdate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_SoftwarUpdate, lv_color_hex(0xE09514), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_SoftwarUpdate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SOFTWARUPDATE_NUM);
    children[UI_COMP_SOFTWARUPDATE_SOFTWARUPDATE] = cui_SoftwarUpdate;
    lv_obj_add_event_cb(cui_SoftwarUpdate, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_SoftwarUpdate, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_SoftwarUpdate_create_hook(cui_SoftwarUpdate);
    return cui_SoftwarUpdate;
}

