// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: CarTouchScreenMiniDisplay

#ifndef _UI_COMP_SOFTWARUPDATE_H
#define _UI_COMP_SOFTWARUPDATE_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT SoftwarUpdate
#define UI_COMP_SOFTWARUPDATE_SOFTWARUPDATE 0
#define _UI_COMP_SOFTWARUPDATE_NUM 1
lv_obj_t * ui_SoftwarUpdate_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
