// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CarTouchScreenMiniDisplay

#ifndef UI_MEMORYERASEVALIDATION_H
#define UI_MEMORYERASEVALIDATION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MemoryEraseValidation
extern void ui_MemoryEraseValidation_screen_init(void);
extern void ui_MemoryEraseValidation_screen_destroy(void);
extern lv_obj_t * ui_MemoryEraseValidation;
extern lv_obj_t * ui_EraseMemoryConfirm;
extern void ui_event_ConfirmErase(lv_event_t * e);
extern lv_obj_t * ui_ConfirmErase;
extern void ui_event_DenyErase(lv_event_t * e);
extern lv_obj_t * ui_DenyErase;
extern lv_obj_t * ui_ConfrimEraseLabel;
extern lv_obj_t * ui_DenyEraseLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

