// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CarTouchScreenMiniDisplay

#include "../ui.h"

lv_obj_t * ui_MemoryEraseValidation = NULL;
lv_obj_t * ui_EraseMemoryConfirm = NULL;
lv_obj_t * ui_ConfirmErase = NULL;
lv_obj_t * ui_DenyErase = NULL;
lv_obj_t * ui_ConfrimEraseLabel = NULL;
lv_obj_t * ui_DenyEraseLabel = NULL;
// event funtions
void ui_event_ConfirmErase(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        UI_ClearNVS(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_MainConfigScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_MainConfigScreen_screen_init);
    }
}

void ui_event_DenyErase(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MainConfigScreen, LV_SCR_LOAD_ANIM_FADE_ON, 250, 0, &ui_MainConfigScreen_screen_init);
    }
}

// build funtions

void ui_MemoryEraseValidation_screen_init(void)
{
    ui_MemoryEraseValidation = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MemoryEraseValidation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_EraseMemoryConfirm = lv_label_create(ui_MemoryEraseValidation);
    lv_obj_set_width(ui_EraseMemoryConfirm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_EraseMemoryConfirm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_EraseMemoryConfirm, 2);
    lv_obj_set_y(ui_EraseMemoryConfirm, -99);
    lv_obj_set_align(ui_EraseMemoryConfirm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_EraseMemoryConfirm, "This will clear all configurations\nDo you want to proceed?");
    lv_obj_set_style_text_align(ui_EraseMemoryConfirm, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_EraseMemoryConfirm, &ui_font_SmallerEmblemaOne, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfirmErase = lv_btn_create(ui_MemoryEraseValidation);
    lv_obj_set_width(ui_ConfirmErase, 150);
    lv_obj_set_height(ui_ConfirmErase, 150);
    lv_obj_set_x(ui_ConfirmErase, 100);
    lv_obj_set_y(ui_ConfirmErase, 49);
    lv_obj_set_align(ui_ConfirmErase, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConfirmErase, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfirmErase, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConfirmErase, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConfirmErase, lv_color_hex(0x3CE34E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfirmErase, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DenyErase = lv_btn_create(ui_MemoryEraseValidation);
    lv_obj_set_width(ui_DenyErase, 150);
    lv_obj_set_height(ui_DenyErase, 150);
    lv_obj_set_x(ui_DenyErase, -102);
    lv_obj_set_y(ui_DenyErase, 51);
    lv_obj_set_align(ui_DenyErase, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DenyErase, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DenyErase, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DenyErase, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DenyErase, lv_color_hex(0xE71D1D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DenyErase, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConfrimEraseLabel = lv_label_create(ui_MemoryEraseValidation);
    lv_obj_set_width(ui_ConfrimEraseLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConfrimEraseLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConfrimEraseLabel, 100);
    lv_obj_set_y(ui_ConfrimEraseLabel, 48);
    lv_obj_set_align(ui_ConfrimEraseLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConfrimEraseLabel, "Yes");
    lv_obj_set_style_text_align(ui_ConfrimEraseLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConfrimEraseLabel, &ui_font_HeadingDegree, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DenyEraseLabel = lv_label_create(ui_MemoryEraseValidation);
    lv_obj_set_width(ui_DenyEraseLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DenyEraseLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DenyEraseLabel, -102);
    lv_obj_set_y(ui_DenyEraseLabel, 55);
    lv_obj_set_align(ui_DenyEraseLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DenyEraseLabel, "No");
    lv_obj_set_style_text_align(ui_DenyEraseLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DenyEraseLabel, &ui_font_HeadingDegree, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ConfirmErase, ui_event_ConfirmErase, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DenyErase, ui_event_DenyErase, LV_EVENT_ALL, NULL);

}

void ui_MemoryEraseValidation_screen_destroy(void)
{
    if(ui_MemoryEraseValidation) lv_obj_del(ui_MemoryEraseValidation);

    // NULL screen variables
    ui_MemoryEraseValidation = NULL;
    ui_EraseMemoryConfirm = NULL;
    ui_ConfirmErase = NULL;
    ui_DenyErase = NULL;
    ui_ConfrimEraseLabel = NULL;
    ui_DenyEraseLabel = NULL;

}
