// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: CarTouchScreenMiniDisplay

#ifndef UI_WIFI_H
#define UI_WIFI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Wifi
extern void ui_Wifi_screen_init(void);
extern void ui_Wifi_screen_destroy(void);
extern void ui_event_Wifi(lv_event_t * e);
extern lv_obj_t * ui_Wifi;
extern lv_obj_t * ui_EnableProvisioning;
extern lv_obj_t * ui_ProvisioningText;
extern lv_obj_t * ui_ConnectedWifiSSID;
extern lv_obj_t * ui_GatewayIP;
extern lv_obj_t * ui_myIPString;
extern void ui_event_ManualConnect(lv_event_t * e);
extern lv_obj_t * ui_ManualConnect;
extern lv_obj_t * ui_Manual_Connect_Text;
extern void ui_event_TriggerWifiScan(lv_event_t * e);
extern lv_obj_t * ui_TriggerWifiScan;
extern lv_obj_t * ui_TriggerWifiScan1;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Wifi;
extern lv_obj_t * uic_EnableProvisioning;
extern lv_obj_t * uic_ProvisioningText;
extern lv_obj_t * uic_ConnectedWifiSSID;
extern lv_obj_t * uic_GatewayIP;
extern lv_obj_t * uic_myIPString;
extern lv_obj_t * uic_TriggerWifiScan;
extern lv_obj_t * uic_TriggerWifiScan1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

